config/routes.rb
Rails.application.routes.draw do
  resources :clones do
  get '/home', to: 'clones#home'
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clone.rb
class Clone < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140, message: '140字以内で入力してください' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clones_controller.rb
class ClonesController < ApplicationController
  before_action :set_clone, only: [:edit, :update, :destroy]

  def home
  end

  def index
    @clones = Clone.all
  end

  def new
    if params[:back]
      @clone = Clone.new(clone_params)
    else
      @clone = Clone.new
    end
  end
  
  def create
    @clone = Clone.create(clone_params) 
    if @clone.save
      redirect_to clones_path
    else
      render 'new'
    end
  end
  
  def edit
    set_clone
  end
  
  def update
    set_clone
    if @clone.update(clone_params)
      redirect_to clones_path, notice: "編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @clone.destroy
    redirect_to clones_path, notice:"つぶやき削除しました！"
  end

  def confirm
    @clone = Clone.new(clone_params)
    render :new if @clone.invalid?
  end
  
  private
  def clone_params
    params.require(:clone).permit(:content)
  end
  
  def set_clone
    @clone = Clone.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clones_helper.rb
module ClonesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_clones_path
    elsif action_name == 'edit'
      clone_path
    end
  end
end

app/views/clones/_form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./css/normalize.css">
    <link rel="stylesheet" href="./css/clones.scss">
    <title>つぶやき一覧</title>
  </head>
  
  <body>
    <div class="container">
    <%= form_with(model: @clone, local: true ,url: choose_new_or_edit ) do |form| %>
      <% if @clone.errors.any? %>
        <div id="error_explanation">
          <h2><%= @clone.errors.count %>件のエラーがあります。</h2>
          <ul>
          <% @clone.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
      
      <div class="clone_title">
        <%= form.label :content %>
        <%= form.text_field :content %>
      </div>
      <%= form.submit "つぶやく" %>
    <% end %>
  </body>
  
  <footer class="footer">
    <p>Copyright © 2018 CLONES INC All RIGHTS RESERVED.</p>
  </footer>
  </div>
  </body>
</html>

app/views/clones/confirm.html.erb
<h3>以下の内容でつぶやきます。</h3>

<%= form_with(model: @clone, url: clones_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>内容:<%= @clone.content %></p>
  <%= form.submit  "つぶやく" %>
<% end %>

<%= form_with(model: @clone, url: new_clone_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/clones/edit.html.erb
<h2>編集する</h2>
  <%= render 'form' %>

app/views/clones/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./css/normalize.css">
    <link rel="stylesheet" href="./css/clones.scss">
    <title>つぶやき一覧</title>
  </head>
  <body>
    <div class="container">
    <header class="header clearfix">
    <nav>
      <ul class="top_menu clearfix">
        <li><%= link_to "ホーム", clone_home_path %></li>
        <li><%= link_to "つぶやき一覧", clones_path %></li>
        <li><%= link_to "つぶやき", new_clone_path %></li>
      </ul>   
    </nav>
    <%= image_tag('shakehand.png', size: '980x600') %>
   </header>
  <footer class="footer">
    <p>Copyright © 2018 CLONES INC All RIGHTS RESERVED.</p>
  </footer>
  </div>
  </body>
</html>

app/views/clones/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="./css/normalize.css">
    <link rel="stylesheet" href="./css/clones.scss">
    <title>つぶやき一覧</title>
  </head>
  <body>   
    <div class="container">
      <h1>つぶやき一覧</h1>
        <p><%= notice %></p>
      
      <table>
        <tr>
          <th>内容</th></th>
        </tr>
      
      <% @clones.each do |clone| %>
        <tr>
          <td><%= clone.content %></td>
          <td class="btn"><%= link_to "[編集]", edit_clone_path(clone.id) %></td>
          <td class="btn"><%= link_to '[削除]', clone_path(clone.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
        </tr>
      <% end %>
      </table>
  
  
  
      <%= link_to 'つぶやく', new_clone_path %>
      
  <footer class="footer">
    <p>Copyright © 2018 CLONES INC All RIGHTS RESERVED.</p>
  </footer>
  </div>
  </body>
</html>

app/views/clones/new.html.erb
<h2>つぶやく</h2>
  <%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample4</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>